/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Trivia.Dificil;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class P3Dificil extends javax.swing.JFrame {

    private int puntaje;
    /**
     * Creates new form P3
     */
    public P3Dificil() {
        initComponents();
    }
    
    private int pistasUsadas;
    private int maxPistas = 2;
    static int id;
 
    
    public P3Dificil(int puntajeRecibido, int pistasUsadasActual,int id) {
    this.puntaje = puntajeRecibido;
    this.pistasUsadas = pistasUsadasActual;
    initComponents();
    jTextField1.setText(String.valueOf(this.puntaje)); 
    jTextField1.setEditable(false);
    if(pistasUsadas >= maxPistas) {
        pista.setEnabled(false); // Deshabilita el botón si ya se alcanzó el máximo al abrir la ventana
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correcta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bad = new javax.swing.JButton();
        bad1 = new javax.swing.JButton();
        bad2 = new javax.swing.JButton();
        pista = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        correcta.setBackground(new java.awt.Color(0, 0, 0));
        correcta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correcta.setForeground(new java.awt.Color(255, 255, 255));
        correcta.setText("Apollo11");
        correcta.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        correcta.setBorderPainted(false);
        correcta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctaActionPerformed(evt);
            }
        });
        getContentPane().add(correcta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 120, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("R:1 P:3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Puntaje: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 0, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿ Qué misión espacial fue la que nos");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 420, 50));

        bad.setBackground(new java.awt.Color(0, 0, 0));
        bad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bad.setForeground(new java.awt.Color(255, 255, 255));
        bad.setText("Apollo13");
        bad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));
        bad.setBorderPainted(false);
        bad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badActionPerformed(evt);
            }
        });
        getContentPane().add(bad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 120, 40));

        bad1.setBackground(new java.awt.Color(0, 0, 0));
        bad1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bad1.setForeground(new java.awt.Color(255, 255, 255));
        bad1.setText("Artemisa");
        bad1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        bad1.setBorderPainted(false);
        bad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bad1ActionPerformed(evt);
            }
        });
        getContentPane().add(bad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, 40));

        bad2.setBackground(new java.awt.Color(0, 0, 0));
        bad2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bad2.setForeground(new java.awt.Color(255, 255, 255));
        bad2.setText("Challenger");
        bad2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));
        bad2.setBorderPainted(false);
        bad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bad2ActionPerformed(evt);
            }
        });
        getContentPane().add(bad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 120, 40));

        pista.setBackground(new java.awt.Color(153, 204, 255));
        pista.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pista.setText("Pista");
        pista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        pista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistaActionPerformed(evt);
            }
        });
        getContentPane().add(pista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, 30));

        jLabel6.setBackground(new java.awt.Color(255, 0, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("llevo a la luna por primera vez ?");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 420, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trivia/Dificil/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correctaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctaActionPerformed
        // TODO add your handling code here:

        puntaje+=10;
        JOptionPane.showMessageDialog(rootPane, "Respuesta correcta ! ");

        
        P4Dificil pregunta4 = new P4Dificil(puntaje,pistasUsadas,id);
        pregunta4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_correctaActionPerformed

    private void badActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badActionPerformed
        // TODO add your handling code here:

        
        JOptionPane.showMessageDialog(rootPane, "Respuesta incorrecta :( ");

        
        puntaje+=0;
        
        
        P4Dificil pregunta4 = new P4Dificil(puntaje,pistasUsadas,id);
        pregunta4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_badActionPerformed

    private void bad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bad1ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(rootPane, "Respuesta incorrecta :( ");

        
        puntaje+=0;
        
        
        P4Dificil pregunta4 = new P4Dificil(puntaje,pistasUsadas,id);
        pregunta4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bad1ActionPerformed

    private void bad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bad2ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(rootPane, "Respuesta incorrecta :( ");

        
        puntaje+=0;
        
        P4Dificil pregunta4 = new P4Dificil(puntaje,pistasUsadas,id);
        pregunta4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bad2ActionPerformed

    private void pistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistaActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(rootPane, "Se lanzó en 1969");
        
           pistasUsadas++;
        
          if(pistasUsadas > maxPistas) {
        pista.setEnabled(false);
    }
    }//GEN-LAST:event_pistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P3Dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P3Dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P3Dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P3Dificil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P3Dificil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bad;
    private javax.swing.JButton bad1;
    private javax.swing.JButton bad2;
    private javax.swing.JButton correcta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton pista;
    // End of variables declaration//GEN-END:variables
}
