package Perfil;
import MenuJuegos.Menu;
import conexiones.SQLConexion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;


/**
 *
 * @author DELL
 */
public class Perfil extends javax.swing.JFrame {
    SQLConexion con= new SQLConexion();
    Connection cn= con.getConectarDB();
    static int id;
    /**
     * Creates new form Perfil
     */
    public Perfil(int id) throws SQLException {
        initComponents();
        this.id=id;
        cargarDatos();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Verpassword = new javax.swing.JButton();
        cambiarusuario = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        cambiarusuario1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 32)); // NOI18N
        jLabel1.setText("Correo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Snap ITC", 0, 32)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 202, 45));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfil/fotoperfil.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 321, 247));

        Verpassword.setText("Ver");
        Verpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Verpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));

        cambiarusuario.setBackground(new java.awt.Color(255, 0, 0));
        cambiarusuario.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        cambiarusuario.setForeground(new java.awt.Color(255, 255, 255));
        cambiarusuario.setText("Actualizar");
        cambiarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 140, 60));

        btnmenu.setBackground(new java.awt.Color(0, 51, 204));
        btnmenu.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        btnmenu.setForeground(new java.awt.Color(255, 255, 255));
        btnmenu.setText("Menu ");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 130, 50));

        jPasswordField1.setEditable(false);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 210, 40));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 1, 32)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 202, 45));

        cambiarusuario1.setBackground(new java.awt.Color(0, 204, 51));
        cambiarusuario1.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        cambiarusuario1.setForeground(new java.awt.Color(255, 255, 255));
        cambiarusuario1.setText("Mis partidas");
        cambiarusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarusuario1ActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 140, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarDatos() throws SQLException{
        String consultasql2=("SELECT correo,contraseña,nombre FROM usuarios WHERE id='"+id+"'");
        
            Statement st2;
            st2 = (Statement) cn.createStatement();
            ResultSet rs2= st2.executeQuery(consultasql2);
            try{
                while(rs2.next()){
                    jPasswordField1.setText(""+rs2.getString(2));
                    jTextField2.setText(""+rs2.getString(1));
                    jTextField3.setText(""+rs2.getString(3));
                 }

            }catch(Exception e){
            JOptionPane.showOptionDialog(null, "Erro00r: "+e.getMessage(), "Error", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, null, EXIT_ON_CLOSE);
        }
        
        
    }
    private void VerpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerpasswordActionPerformed
        // TODO add your handling code here:
        
        if (jPasswordField1.getEchoChar() == 0) {
            // La contraseña ya se está mostrando, cambia a modo oculto
            jPasswordField1.setEchoChar('*');
            Verpassword.setText("Ver");
        } else {
            // Cambia a mostrar la contraseña en texto claro
            jPasswordField1.setEchoChar((char) 0);
            Verpassword.setText("Ocultar");
        }
    }//GEN-LAST:event_VerpasswordActionPerformed

    private void cambiarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarusuarioActionPerformed
        // TODO add your handling code here:
        
        ActualizarUsuario cambiaruser = null;
        try {
            cambiaruser = new ActualizarUsuario(id);
        } catch (SQLException ex) {
            Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        cambiaruser.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_cambiarusuarioActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(id);
        menu.setVisible(true);
        this.dispose(); //funcion para cerrar ventana anterior

    }//GEN-LAST:event_btnmenuActionPerformed

    private void cambiarusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarusuario1ActionPerformed
        VistaMisPartida a= new VistaMisPartida(id);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambiarusuario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Perfil(id).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verpassword;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton cambiarusuario;
    private javax.swing.JButton cambiarusuario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
