/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PuzzleMenu;
import MenuJuegos.Menu;
import PuzzleMenu.Facil.Luna.PuzzleLuna;
import PuzzleMenu.Facil.Marte.PuzzleMarte;
import PuzzleMenu.Facil.SistemaSolar.PuzzleSistemaSolarFacil;
import PuzzleMenu.Facil.Tierra.PuzzleTierra;
import PuzzleMenu.Facil.Sol.PuzzleSol;
import PuzzleMenu.Medio.Apollo.PuzzleApollo;
import PuzzleMenu.Medio.Orion.PuzzleOrion;
import PuzzleMenu.Medio.OsaMayor.PuzzleOsaMayor;
import PuzzleMenu.Medio.ViaLactea.PuzzleViaLactea;
import PuzzleMenu.Dificil.HoyoNegro.PuzzleHoyoNegro;
import PuzzleMenu.Dificil.Hubble.PuzzleHubble;
import PuzzleMenu.Dificil.SistemaSolarDificil.PuzzleSistemaSolarDificil;
/**
 *
 * @author 177192
 */
public class PuzzleMenu extends javax.swing.JFrame {
   static int id;
   private static int puntajeTotal=0;
    
    
    public PuzzleMenu(int id) {
        initComponents();
        this.id=id;
    }

    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
 
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnmenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSistemaS = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        botontierra = new javax.swing.JButton();
        botonluna = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnMarte = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnSol = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnOsa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        botonapolo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnOrion = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnGalaxia = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnHubble = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnSistemaMedio = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnSistemaDificil = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnBlackHole = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 850));
        setPreferredSize(new java.awt.Dimension(1320, 850));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Snap ITC", 3, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ROMPECABEZAS ESPACIAL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("ASTROFISICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("ASTRONAUTA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Snap ITC", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("COSMOLOGO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, -1, -1));

        btnmenu.setBackground(new java.awt.Color(0, 51, 204));
        btnmenu.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        btnmenu.setForeground(new java.awt.Color(255, 255, 255));
        btnmenu.setText("Menu ");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/earth.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/luna.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        btnSistemaS.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnSistemaS.setText("ARMAR");
        btnSistemaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaSActionPerformed(evt);
            }
        });
        getContentPane().add(btnSistemaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/merlin_172064805_d476abdd-f4da-4015-8ca3-8c45c92c61fa-articleLarge.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        botontierra.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        botontierra.setText("ARMAR");
        botontierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botontierraActionPerformed(evt);
            }
        });
        getContentPane().add(botontierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        botonluna.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        botonluna.setText("ARMAR");
        botonluna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlunaActionPerformed(evt);
            }
        });
        getContentPane().add(botonluna, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/Mars.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        btnMarte.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnMarte.setText("ARMAR");
        btnMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarteActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/sistemasolar.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 250, 130));

        btnSol.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnSol.setText("ARMAR");
        btnSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolActionPerformed(evt);
            }
        });
        getContentPane().add(btnSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/osa_mayor.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        btnOsa.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnOsa.setText("ARMAR");
        btnOsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsaActionPerformed(evt);
            }
        });
        getContentPane().add(btnOsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/apollo11.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        botonapolo.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        botonapolo.setText("ARMAR");
        botonapolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonapoloActionPerformed(evt);
            }
        });
        getContentPane().add(botonapolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/constelacixn_de_orixn.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        btnOrion.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnOrion.setText("ARMAR");
        btnOrion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrionActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/milkyway.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, -1, -1));

        btnGalaxia.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnGalaxia.setText("ARMAR");
        btnGalaxia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGalaxiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGalaxia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/Hubble_01_Cropped (1).jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, -1, -1));

        btnHubble.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnHubble.setText("ARMAR");
        btnHubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHubbleActionPerformed(evt);
            }
        });
        getContentPane().add(btnHubble, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 330, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/sistemasolar.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 250, 130));

        btnSistemaMedio.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnSistemaMedio.setText("ARMAR");
        btnSistemaMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaMedioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSistemaMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 670, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/sistemasolar.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 250, 130));

        btnSistemaDificil.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnSistemaDificil.setText("ARMAR");
        btnSistemaDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaDificilActionPerformed(evt);
            }
        });
        getContentPane().add(btnSistemaDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 740, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/supermassive_blackhole_planet.jpg"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 370, 260, 170));

        btnBlackHole.setFont(new java.awt.Font("Snap ITC", 1, 18)); // NOI18N
        btnBlackHole.setText("ARMAR");
        btnBlackHole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlackHoleActionPerformed(evt);
            }
        });
        getContentPane().add(btnBlackHole, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 550, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PuzzleMenu/222a0332bd69330e9ac4109495a420ca.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(id);
        menu.setVisible(true);
        this.dispose(); //funcion para cerrar ventana anterior
        
    }//GEN-LAST:event_btnmenuActionPerformed

    private void botonlunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlunaActionPerformed
        // TODO add your handling code here:
        
        PuzzleLuna puzzleluna = new PuzzleLuna(id);
        puzzleluna.setVisible(true);

        this.dispose(); //funcion para cerrar ventana anterior
   
      
    }//GEN-LAST:event_botonlunaActionPerformed

    private void btnMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarteActionPerformed
        // TODO add your handling code here:
        
        PuzzleMarte puzzlemarte = new PuzzleMarte(id);
        puzzlemarte.setVisible(true);
        this.dispose(); //funcion para cerrar ventana anterior
   
    }//GEN-LAST:event_btnMarteActionPerformed

    private void btnSistemaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaSActionPerformed
        // TODO add your handling code here:
        PuzzleSistemaSolarFacil puzzlessfacil = new PuzzleSistemaSolarFacil(id);
        puzzlessfacil.setVisible(true);
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnSistemaSActionPerformed

    private void botontierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botontierraActionPerformed
        // TODO add your handling code here:
        
        PuzzleTierra puzzletierra = new PuzzleTierra(id);
        puzzletierra.setVisible(true);
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_botontierraActionPerformed

    private void btnSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolActionPerformed
        // TODO add your handling code here:
        PuzzleSol puzzlesol = new PuzzleSol(id);
        puzzlesol.setVisible(true);
        ContadorPuzzle.incrementar();
        ContadorPuzzle.incrementarfacil();
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnSolActionPerformed

    private void btnOsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsaActionPerformed
        // TODO add your handling code here:
        
        PuzzleOsaMayor puzzleosamayor = new PuzzleOsaMayor(id);
        puzzleosamayor.setVisible(true);
        ContadorPuzzle.incrementar();
        ContadorPuzzle.incrementarmedio();
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnOsaActionPerformed

    private void botonapoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonapoloActionPerformed
        // TODO add your handling code here:
        PuzzleApollo puzzleapollo = new PuzzleApollo(id);
        puzzleapollo.setVisible(true);  
        ContadorPuzzle.incrementar();
        ContadorPuzzle.incrementarmedio();
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_botonapoloActionPerformed

    private void btnOrionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrionActionPerformed
        // TODO add your handling code here:
        PuzzleOrion puzzleorion = new PuzzleOrion(id);
        puzzleorion.setVisible(true);   
        ContadorPuzzle.incrementar();
        ContadorPuzzle.incrementarmedio();
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnOrionActionPerformed

    private void btnGalaxiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGalaxiaActionPerformed
        // TODO add your handling code here:
        PuzzleViaLactea puzzlevialactea = new PuzzleViaLactea(id);
        puzzlevialactea.setVisible(true);    
        ContadorPuzzle.incrementar();
        ContadorPuzzle.incrementarmedio();
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnGalaxiaActionPerformed

    private void btnSistemaMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaMedioActionPerformed
        // TODO add your handling code here:
        PuzzleLuna puzzlesol = new PuzzleLuna(id);
        puzzlesol.setVisible(true);     
        ContadorPuzzle.incrementar();
        ContadorPuzzle.incrementarmedio();
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnSistemaMedioActionPerformed

    private void btnHubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHubbleActionPerformed
        // TODO add your handling code here:
        
        PuzzleHubble puzzlehubble = new PuzzleHubble(id);
        puzzlehubble.setVisible(true);  
        ContadorPuzzle.incrementar();
        ContadorPuzzle.incrementardificil();
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnHubbleActionPerformed

    private void btnBlackHoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlackHoleActionPerformed
        // TODO add your handling code here:
        PuzzleHoyoNegro puzzleblackhole = new PuzzleHoyoNegro(id);
        puzzleblackhole.setVisible(true);
        ContadorPuzzle.incrementar();
        ContadorPuzzle.incrementardificil();
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnBlackHoleActionPerformed

    private void btnSistemaDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaDificilActionPerformed
        // TODO add your handling code here:
        PuzzleSistemaSolarDificil puzzlesistemasolardificil = new PuzzleSistemaSolarDificil(id);
        puzzlesistemasolardificil.setVisible(true);
        this.dispose(); //funcion para cerrar ventana anterior
    }//GEN-LAST:event_btnSistemaDificilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuzzleMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuzzleMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuzzleMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuzzleMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuzzleMenu(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonapolo;
    private javax.swing.JButton botonluna;
    private javax.swing.JButton botontierra;
    private javax.swing.JButton btnBlackHole;
    private javax.swing.JButton btnGalaxia;
    private javax.swing.JButton btnHubble;
    private javax.swing.JButton btnMarte;
    private javax.swing.JButton btnOrion;
    private javax.swing.JButton btnOsa;
    private javax.swing.JButton btnSistemaDificil;
    private javax.swing.JButton btnSistemaMedio;
    private javax.swing.JButton btnSistemaS;
    private javax.swing.JButton btnSol;
    private javax.swing.JButton btnmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
